# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170329_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='There is currently no description available for this project.', max_length=4000),
            preserve_default=False,
        ),
    ]
