# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
