# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
