# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170417_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
